_target_: ib.models.inrs.sirenfm.SirenFm
in_features: 3
mod_hidden_size: 256
hidden_features: 256
hidden_layers: 3
out_features: 1
###
num_frequencies: 10
first_omega: 10
hidden_omega: 10
modulator_path: "/home/magnes/repos/inductive_biases/modulator_256_softplus_relu_abc.pt"
