# Defaults.
defaults:
  # Scene is required.
  - scene: ???
  - inr: siren
  - loss: siren_sdf_loss
  # Only base variants.
  - trainer: base_trainer
  - model: base_model
  # Disable logs from Hydra.
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

# Global flags.
run_name: default
output_dir_root: ${oc.env:HOME}/outputs/

# Paths
paths: null

# Supress hydra outputs for now.
hydra:
  output_subdir: null
  run:
    dir: .