# Scannet++, id: 5fb5d2dbf2
# uv run preprocessing --input-path=~/datasets/3d_scenes/scannet_room_3/pc_aligned.ply --x-range -0.61 0.6 --y-range -0.8 0.2 --z-range -1.0 0.1 --rotation-angle 1.0 --margin 0.005
defaults:
  - dataset: ply_dataset

name: scannet_room_3
file_path: ${oc.env:HOME}/datasets/3d_scenes/scannet_room_3/pc_aligned_filtered_trimmed_both_0005.ply