# https://drive.google.com/drive/folders/1_iq__37-hw7FJOEUK1tX7mdp8SKB368K

defaults:
  - dataset: xyz_dataset

name: thai_statue
file_path: ${oc.env:HOME}/datasets/3d_scenes/thai_statue/thai_statue.xyz
