# Devices
num_workers: 8
persistent_workers: True
accelerator: gpu
devices: 1
float32_matmul_precision: high
prefetch_factor: 4

# Training
max_epochs: 3000
batch_size: 100000
lr: 1e-4
weight_decay: 0.0
gradient_clip_val: 1.0
save_model_every_n_epochs: 500
eval_model_every_n_epochs: 500

# Debug
limit_train_batches: null
fast_dev_run: False
seed: null

# Logging
run_name: ${run_name}

# Paths
paths: ${paths}
