# Devices
num_workers: 8
persistent_workers: True
accelerator: gpu
devices: 1
float32_matmul_precision: highest

# Training
max_epochs: 20000
batch_size: 150000
lr: 1e-4
gradient_clip_val: 1.0
save_model_every_n_epochs: 500

# Debug
limit_train_batches: null
fast_dev_run: False

# Paths
paths: ${paths}
