# Wrap external configs.
inr: ${inr}
loss: ${loss}
lr: ${trainer.lr}
weight_decay: ${trainer.weight_decay}
save_model_every_n_epochs: ${trainer.save_model_every_n_epochs}
eval_model_every_n_epochs: ${trainer.eval_model_every_n_epochs}
max_epochs: ${trainer.max_epochs}
paths: ${paths}